import { log as logger } from '../Log.js';
var log = logger.Logger('PayInvoice');

import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Alert, Card, CardHeader, CardBody, Row, Col } from 'reactstrap';

import { ErrorWrapper } from '../components/ErrorWrapper.jsx';
import { Notifier } from '../Notifier.js';
import { getPriceCents, labPrice, labUserPrice } from './calculations.js';
import { PaymentElementModal } from './PaymentElementModal.jsx';
import { PaymentMethod } from './PaymentMethod.jsx';
import { initiatePurchase } from './actions.js';

import { LoadingSpinner } from '../LoadingSpinner.js';
import { formatCurrency } from '../Utils.js';
import { dateFormatOptions } from './constants.js';

const storageLevelDescriptions = {
	2: '2 GB',
	3: '6 GB',
	6: 'Unlimited storage'
};

// component that handles paying an invoice that has been generated by a user for a third party to pay
function PayInvoice(props) {
	log.debug("PayInvoice");
	log.debug(props);
	const { invoice, invoiceUser, institutionName, overQuota } = props;
	const { invoiceID, invoiceType, stripeCharge, numUsers, storageLevel, created } = invoice;
	
	const [ stripeIntent, setStripeIntent ] = useState(null);
	const [ purchase, setPurchase ] = useState({
		invoiceID: invoiceID,
		type: invoiceType,
		storageLevel,
		numUsers,
		immediateCharge: true
	});
	
	const [stripeChargeObject, setStripeChargeObject] = useState(props.stripeChargeObject);
	
	const [invoicePaid, setInvoicePaid] = useState(!!stripeCharge);
	
	let description = [];
	let chargeAmount = 0;
	let error = null;
	let createdDate = new Date(created);
	
	const [notification, setNotification] = useState(null);
	const [operationPending, setOperationPending] = useState(false);
	
	if (!props.invoice) {
		throw new Error("No invoice");
		return null;
	}
	
	switch (invoiceType) {
	case 'individual':
		description.push(`Zotero Storage subscription for user ${invoiceUser.username} - ${invoiceUser.email}`);
		description.push(`1 year of Zotero file storage: ${storageLevelDescriptions[storageLevel]}`);
		chargeAmount = getPriceCents('US')[storageLevel];
		break;
	case 'lab':
		if (institutionName) {
			description.push(`${institutionName}`);
		}
		description.push(`Zotero Lab subscription managed by user ${invoiceUser.username} - ${invoiceUser.email}`);
		description.push(`Zotero Lab subscription will provide one year of unlimited Zotero file storage for ${numUsers} users`);
		chargeAmount = labPrice(numUsers);
		break;
	case 'addLabUsers':
		if (institutionName) {
			description.push(`${institutionName}`);
		}
		description.push(`Add ${numUsers} users to existing Zotero Lab subscription managed by user ${invoiceUser.username} - ${invoiceUser.email}`);
		chargeAmount = labUserPrice(numUsers);
		break;
	case 'contribution':
		break;
	default:
		log.error(invoiceType);
		throw new Error('Unknown invoice type');
	}
	if (invoiceType == 'individual' && overQuota) {
		error = <Alert color='error'>Current usage exceeds the chosen plan&apos;s quota. You&apos;ll need to choose a larger storage plan, or delete some files from your Zotero storage.</Alert>;
	}
	
	let descriptionPs = description.map((d, i) => {
		return <p key={i}>{d}</p>;
	});
	
	useEffect(() => {
		log.debug("useEffect initiatePurchase");
		const startPurchase = async () => {
			log.debug(purchase);
			if (!stripeIntent && !stripeChargeObject) {
				if (purchase.immediateCharge || purchase.type=='individualPaymentUpdate') {
					setOperationPending(true);
					let purchaseData = Object.assign({}, purchase, { type: 'chargePayableInvoice'});
					await initiatePurchase(purchaseData, setStripeIntent);
					setOperationPending(false);
				}
			}
		};
		startPurchase();
	}, [purchase, chargeAmount]);

	
	// processing is done in webhook and payment confirmation in PaymentElement.
	// No payment modal here or subscription details, so do nothing.
	const handleConfirmIntent = async (stripeIntent) => {
		log.debug('PayInvoice:handleConfirmIntent - noop');
		log.debug(stripeIntent);
		setPurchase(null);
		return;
		//TODO: get charge details and update so we display paid invoice?
	};
	
	let buttonLabel = `Pay ${formatCurrency(chargeAmount)}`;
	
	let paymentSection = null;
	if (!invoicePaid) {
		log.debug(description);
		
		const callbacks = {
			handleConfirmIntent,
			setOperationPending,
			setNotification,
		};

		let storageState = {
			purchase,
			stripeIntent,
			description,
			stripeCustomer,
		}
		paymentSection = <PaymentElementModal
			stripe={window.stripe}
			{...{
				storageState,
				callbacks,
				// autorenew,
				// setAutorenew,
				buttonLabel,
				useEmail: true,
				cancelable: false,
				returnUrl: window.location.toString(),
			}}
		/>;
		/*
		paymentSection = <PaymentElementModal
			stripe={window.stripe}
			{...{
				callbacks,
				purchase,
				stripeIntent,
				chargeAmount,
				operationPending,
				buttonLabel,
				useEmail: true,
				cancelable: false,
				returnUrl: window.location.toString(),
			}}
			chargeDescription={storageLevel ? storageLevelDescriptions[storageLevel] : "Update payment method"}
		/>;
		*/
	} else {
		const paymentMethodDetails = stripeChargeObject.payment_method_details;
		log.debug(paymentMethodDetails);
		log.debug(stripeChargeObject);
		descriptionPs = <p>{stripeChargeObject.description}</p>;
		let datePaid = new Date(stripeChargeObject.created * 1000);
		
		if (paymentMethodDetails) {
			paymentSection = (
				<div className='currentPaymentMethod'>
					<Card>
						<CardHeader>
							<h3>Invoice Paid - {datePaid.toLocaleDateString('en-US', dateFormatOptions)}</h3>
						</CardHeader>
						<CardBody>
							<h4>Payment Method</h4>
							<PaymentMethod source={paymentMethodDetails} />
						</CardBody>
					</Card>
				</div>
			);
		}
	}
	
	return (
		<ErrorWrapper>
			<div className='pay-invoice'>
				<Row>
					<Col sm={{ size: 4, offset: 2 }}>
						<h3>Invoice ID</h3>
						<p>{invoice.invoiceID}</p>
						<p>{createdDate.toLocaleDateString('en-US', dateFormatOptions)}</p>
					</Col>
					<Col sm={4}>
						<h3>Invoice For:</h3>
						<div id='user_info'>
							<p>{invoiceUser.username}</p>
							<p>{invoiceUser.email}</p>
							<p></p>
						</div>
					</Col>
				</Row>
				<Row>
					<Col sm={{ size: 8, offset: 2 }}>
						<Notifier {...notification} />
						<Card className='payment-card'>
							<CardHeader>Zotero Subscription Invoice</CardHeader>
							<CardBody>
								<LoadingSpinner className='m-auto' loading={operationPending} />
								<Card className='mb-4'>
									<CardBody>
										{error}
										{descriptionPs}
									</CardBody>
								</Card>
								{paymentSection}
							</CardBody>
						</Card>
					</Col>
				</Row>
			</div>
		</ErrorWrapper>
	);
}

PayInvoice.propTypes = {
	invoice: PropTypes.shape({
		invoiceID: PropTypes.string.isRequired,
		invoiceType: PropTypes.string.isRequired,
		stripeCharge: PropTypes.string,
		userID: PropTypes.number,
		institutionID: PropTypes.number,
		numUsers: PropTypes.number,
		storageLevel: PropTypes.number,
		created: PropTypes.string
	}).isRequired,
	invoiceUser: PropTypes.shape({
		userID: PropTypes.number,
		username: PropTypes.string,
		email: PropTypes.string
	}),
	overQuota: PropTypes.bool,
	stripeCustomer: PropTypes.object,
	stripeChargeObject: PropTypes.shape({
		payment_method_details: PropTypes.object,
		created: PropTypes.number,
	}),
	institutionName: PropTypes.oneOfType([PropTypes.string, PropTypes.bool])
};

export { PayInvoice };
