import { log as logger } from '../Log.js';
var log = logger.Logger('PayInvoice');

import { useState, useEffect } from 'react';
import PropTypes from 'prop-types';
import { Alert, Card, CardHeader, CardBody, Row, Col } from 'reactstrap';

import { ErrorWrapper } from '../components/ErrorWrapper.jsx';
import { Notifier } from '../Notifier.js';
import { priceCents, labPrice, labUserPrice } from './calculations.js';
import { PaymentElementModal } from './PaymentElementModal.jsx';
import { PaymentSource } from './PaymentSource.jsx';

import { ajax } from '../ajax.js';
import { LoadingSpinner } from '../LoadingSpinner.js';
import { formatCurrency } from '../Utils.js';

const dateFormatOptions = { year: 'numeric', month: 'long', day: 'numeric' };

const storageLevelDescriptions = {
	2: '2 GB',
	3: '6 GB',
	6: 'Unlimited storage'
};

// async function beginIntent(amount, description, storageLevel, immediateCharge) {
async function beginIntent(purchase, setIntent) {
	log.debug(`beginIntent:`);
	log.debug(purchase);
	let purchaseData = Object.assign({}, purchase, { type: 'chargePayableInvoice'});// Object.assign({}, purchase, { paymentMethod: paymentMethod.id });
	log.debug(purchaseData);
	// let args = { amount, description, storageLevel, immediateCharge };
	let resp = await ajax({
		url: '/storage/newstripeintent',
		type: 'POST',
		withSession: true,
		data: JSON.stringify(purchaseData),
	});

	log.debug(resp, 4);
	let data = await resp.json();
	log.debug(data);
	if (data.success) {
		log.debug('successful beginIntent');
		setIntent(data);
		return data.client_secret;
	} else {
		throw data;
	}
}

// component that handles paying an invoice that has been generated by a user for a third party to pay
function PayInvoice(props) {
	log.debug("PayInvoice");
	log.debug(props);
	const { invoice, invoiceUser, institutionName, overQuota } = props;
	const { invoiceID, invoiceType, stripeCharge, numUsers, storageLevel, created } = invoice;
	
	const [ paymentIntent, setIntent ] = useState(null);
	const [ purchase, setPurchase ] = useState({
		invoiceID: invoice.invoiceID,
		type: invoiceType,
		storageLevel,
		numUsers,
		immediateCharge: true
	});
	
	const [stripeChargeObject, setStripeChargeObject] = useState(props.stripeChargeObject);
	
	const [invoicePaid, setInvoicePaid] = useState(!!stripeCharge);
	
	let description = [];
	let chargeAmount = 0;
	let error = null;
	let createdDate = new Date(created);
	
	const [notification, setNotification] = useState(null);
	const [operationPending, setOperationPending] = useState(false);
	
	if (!props.invoice) {
		throw new Error("No invoice");
		return null;
	}
	
	switch (invoiceType) {
	case 'individual':
		description.push(`Zotero Storage subscription for user ${invoiceUser.username} - ${invoiceUser.email}`);
		description.push(`1 year of Zotero file storage: ${storageLevelDescriptions[storageLevel]}`);
		chargeAmount = priceCents[storageLevel];
		break;
	case 'lab':
		if (institutionName) {
			description.push(`${institutionName}`);
		}
		description.push(`Zotero Lab subscription managed by user ${invoiceUser.username} - ${invoiceUser.email}`);
		description.push(`Zotero Lab subscription will provide one year of unlimited Zotero file storage for ${numUsers} users`);
		chargeAmount = labPrice(numUsers);
		break;
	case 'addLabUsers':
		if (institutionName) {
			description.push(`${institutionName}`);
		}
		description.push(`Add ${numUsers} users to existing Zotero Lab subscription managed by user ${invoiceUser.username} - ${invoiceUser.email}`);
		chargeAmount = labUserPrice(numUsers);
		break;
	case 'contribution':
		break;
	default:
		log.error(invoiceType);
		throw new Error('Unknown invoice type');
	}
	if (invoiceType == 'individual' && overQuota) {
		error = <Alert color='error'>Current usage exceeds the chosen plan&apos;s quota. You&apos;ll need to choose a larger storage plan, or delete some files from your Zotero storage.</Alert>;
	}
	
	let descriptionPs = description.map((d, i) => {
		return <p key={i}>{d}</p>;
	});
	
	useEffect(async () => {
		log.debug("useEffect beginIntent");
		log.debug(purchase);
		if (!paymentIntent && !stripeChargeObject) {
			if (purchase.immediateCharge || purchase.type=='individualPaymentUpdate') {
				setOperationPending(true);
				await beginIntent(purchase, setIntent);
				setOperationPending(false);
			}
		}
	}, [purchase, chargeAmount]);

	
	const handleConfirm = async () => {
		log.debug('handleConfirm - noop');
		return;
		/*
		// log.debug(paymentMethod);
		if (operationPending) {
			log.debug('operation already pending');
			return;
		}
		let response;
		let result;
		setOperationPending(true);
		let purchaseData = Object.assign({}, { type: 'chargePayableInvoice' });// Object.assign({}, purchase, { paymentMethod: paymentMethod.id });
		log.debug(purchaseData);
		try {
			response = await ajax({
				type: 'POST',
				withSession: true,
				url: '/storage/purchase',
				data: JSON.stringify(purchaseData),
				throwOnError: false,
			});
		} catch (unexpectedThrownResponse) {
			log.error("UNEXPECTED THROWN RESPONSE WHEN ATTEMPTING PURCHASE");
		} finally {
			log.debug('got response from handleConfirm');
			result = await response.json();
			log.debug(result);
			let notifyType = result.success ? 'success' : 'error';
			let notifyMessage = result.message;

			if (!result.success && result.requires_action) {
				const stripe = window.stripe;
				let confirmResult;
				if (paymentMethod.type == 'card') {
					confirmResult = await stripe.confirmCardPayment(result.client_secret);
				} else if (paymentMethod.type == 'sepa_debit') {
					confirmResult = await stripe.confirmSepaDebitPayment(result.client_secret);
				}
				log.debug(confirmResult);
				if (confirmResult.error) {
					log.debug('confirmResult error');
					notifyType = 'error';
				} else if (confirmResult.paymentIntent) {
					log.debug('confirmResult paymentIntent');
					// resumbmit the purchase with the paymentIntent so the subscription gets updated
					let resubPurchaseData = Object.assign({}, purchaseData, { paymentIntentID: confirmResult.paymentIntent.id });
					response = await ajax({
						type: 'POST',
						withSession: true,
						url: '/storage/purchase',
						data: JSON.stringify(resubPurchaseData),
						throwOnError: false,
					});
					log.debug('got response from resubmitted handleConfirm');
					result = await response.json();
					log.debug(result);
					notifyType = result.success ? 'success' : 'error';
					notifyMessage = result.message;
				}
			}

			// refresh(storageDispatch, paymentDispatch);
			setNotification({type: notifyType, message: notifyMessage});
			
			if (result.success) {
				setStripeChargeObject(result.stripeChargeObject);
				setInvoicePaid(true);
				setOperationPending(false);
			} else {
				log.error('Payment was not processed successfully');
				log.error(result);
			}
			setOperationPending(false);
		}
		*/
	};
	
	let buttonLabel = `Pay ${formatCurrency(chargeAmount)}`;
	
	let paymentSection = null;
	if (!invoicePaid) {
		log.debug(description);
		
		paymentSection = <PaymentElementModal
			stripe={window.stripe}
			{...{
				purchase,
				paymentIntent,
				immediateChargeRequired: true,
				handleConfirm,
				chargeAmount,
				operationPending,
				setOperationPending,
				setNotification,
				buttonLabel,
				useEmail: true,
				cancelable: false,
				returnUrl: window.location.toString(),
			}}
			chargeDescription={storageLevel ? storageLevelDescriptions[storageLevel] : "Update payment method"}
		/>;
	} else {
		const paymentMethodDetails = stripeChargeObject.payment_method_details;
		log.debug(paymentMethodDetails);
		log.debug(stripeChargeObject);
		descriptionPs = <p>{stripeChargeObject.description}</p>;
		let datePaid = new Date(stripeChargeObject.created * 1000);
		
		if (paymentMethodDetails) {
			paymentSection = (
				<div className='currentPaymentSource'>
					<Card>
						<CardHeader>
							<h3>Invoice Paid - {datePaid.toLocaleDateString('en-US', dateFormatOptions)}</h3>
						</CardHeader>
						<CardBody>
							<h4>Payment Method</h4>
							<PaymentSource source={paymentMethodDetails} />
						</CardBody>
					</Card>
				</div>
			);
		}
	}
	
	return (
		<ErrorWrapper>
			<div className='pay-invoice'>
				<Row>
					<Col sm={{ size: 4, offset: 2 }}>
						<h3>Invoice ID</h3>
						<p>{invoice.invoiceID}</p>
						<p>{createdDate.toLocaleDateString('en-US', dateFormatOptions)}</p>
					</Col>
					<Col sm={4}>
						<h3>Invoice For:</h3>
						<div id='user_info'>
							<p>{invoiceUser.username}</p>
							<p>{invoiceUser.email}</p>
							<p></p>
						</div>
					</Col>
				</Row>
				<Row>
					<Col sm={{ size: 8, offset: 2 }}>
						<Notifier {...notification} />
						<Card className='payment-card'>
							<CardHeader>Zotero Subscription Invoice</CardHeader>
							<CardBody>
								<LoadingSpinner className='m-auto' loading={operationPending} />
								<Card className='mb-4'>
									<CardBody>
										{error}
										{descriptionPs}
									</CardBody>
								</Card>
								{paymentSection}
							</CardBody>
						</Card>
					</Col>
				</Row>
			</div>
		</ErrorWrapper>
	);
}

PayInvoice.propTypes = {
	invoice: PropTypes.shape({
		invoiceID: PropTypes.string.isRequired,
		invoiceType: PropTypes.string.isRequired,
		stripeCharge: PropTypes.string,
		userID: PropTypes.number,
		institutionID: PropTypes.number,
		numUsers: PropTypes.number,
		storageLevel: PropTypes.number,
		created: PropTypes.string
	}).isRequired,
	invoiceUser: PropTypes.shape({
		userID: PropTypes.number,
		username: PropTypes.string,
		email: PropTypes.string
	}),
	overQuota: PropTypes.bool,
	stripeCustomer: PropTypes.object,
	stripeChargeObject: PropTypes.shape({
		payment_method_details: PropTypes.object,
		created: PropTypes.number,
	}),
	institutionName: PropTypes.oneOfType([PropTypes.string, PropTypes.bool])
};

export { PayInvoice };
